# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-BibTeX-BibStyle
version:      0.03
version_from: lib/Text/BibTeX/BibStyle.pm
installdirs:  site
requires:
    HTML::Entities:                0
    Text::ASCIIMathML:             0.7
    Text::BibTeX:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
